# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kafka.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kafka.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bkafka.proto\x12\x05kafka\";\n\x0eProduceRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"3\n\x0fProduceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"J\n\x0e\x43onsumeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\x05\x12\x16\n\x0e\x63onsumer_group\x18\x03 \x01(\t\"=\n\x0f\x43onsumeResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x32\x93\x01\n\x0cKafkaService\x12?\n\x0eProduceMessage\x12\x15.kafka.ProduceRequest\x1a\x16.kafka.ProduceResponse\x12\x42\n\x0f\x43onsumeMessages\x12\x15.kafka.ConsumeRequest\x1a\x16.kafka.ConsumeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kafka_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCEREQUEST']._serialized_start=22
  _globals['_PRODUCEREQUEST']._serialized_end=81
  _globals['_PRODUCERESPONSE']._serialized_start=83
  _globals['_PRODUCERESPONSE']._serialized_end=134
  _globals['_CONSUMEREQUEST']._serialized_start=136
  _globals['_CONSUMEREQUEST']._serialized_end=210
  _globals['_CONSUMERESPONSE']._serialized_start=212
  _globals['_CONSUMERESPONSE']._serialized_end=273
  _globals['_KAFKASERVICE']._serialized_start=276
  _globals['_KAFKASERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
